In [4]:
import pandas as pd
import numpy as np

In [2]:
# Main Difference between python list and Numpy array is the size

In [2]:
import time
import sys

In [3]:
li = range(1000)

print(sys.getsizeof(5)*len(li))

28000


In [6]:
ar = np.arange(1000)
print(ar.size*ar.itemsize)

4000


In [ ]:
# li is the python list meanwhile ar is the numpy array


In [ ]:
#  If we measure time taken by python list nd numpy array , numpy array 
# takes less time to performe operartion

In [8]:
size = 1000000
l1 = range(size)
l2 = range(size)


a1 = np.arange(size)
a2 = np.arange(size)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print('Time taken for python list',(time.time()-start)*1000) #to convert milisecond to second


# numpy array
start = time.time()
result = a1 + a2
print('Time taken by numpy array',(time.time()-start)*1000)

Time taken for python list 107.7728271484375
Time taken by numpy array 14.958858489990234


In [9]:
np.linspace(1,5,25)
# generating linearly spaced number between a boundry

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        , 2.16666667, 2.33333333, 2.5       ,
       2.66666667, 2.83333333, 3.        , 3.16666667, 3.33333333,
       3.5       , 3.66666667, 3.83333333, 4.        , 4.16666667,
       4.33333333, 4.5       , 4.66666667, 4.83333333, 5.        ])

In [19]:
a = np.array([[2,98],[9,56],[78,3]])

a.shape


(3, 2)

In [20]:
a

array([[ 2, 98],
       [ 9, 56],
       [78,  3]])

In [23]:
a.reshape(2,3)

array([[ 2, 98,  9],
       [56, 78,  3]])

In [24]:
a.ravel() #flatterning the array

array([ 2, 98,  9, 56, 78,  3])

In [25]:
# axis 0  column wise/ axis 1 row wise
a

array([[ 2, 98],
       [ 9, 56],
       [78,  3]])

In [26]:
a.sum(axis = 0)

array([ 89, 157])

In [27]:
a.sum(axis = 1)

array([100,  65,  81])

In [40]:
b1 = np.array([[1,2],[3,4]])

In [41]:
b2 = np.array([[7,8],[9,10]])

In [42]:
b1.dot(b2) #Matrix product

array([[25, 28],
       [57, 64]])

In [ ]:
# indexing and slicing


In [43]:
a[0:2]

array([[ 2, 98],
       [ 9, 56]])

In [45]:
a[-1]

array([78,  3])

In [46]:
arr = np.array([[6,7,8],[56,90,2],[12,10,5]])

In [48]:
arr

array([[ 6,  7,  8],
       [56, 90,  2],
       [12, 10,  5]])

In [49]:
arr[1,2]

2

In [50]:
arr[0:2,2]

array([8, 2])

In [51]:
arr[-1]

array([12, 10,  5])

In [52]:
arr[-1,0:2]

array([12, 10])

In [53]:
arr[:,1:3]

array([[ 7,  8],
       [90,  2],
       [10,  5]])

In [54]:
a

array([[ 2, 98],
       [ 9, 56],
       [78,  3]])

In [56]:
a2

array([[ 8,  1],
       [12,  6],
       [ 6,  1]])

In [57]:
np.vstack((a,a2))

array([[ 2, 98],
       [ 9, 56],
       [78,  3],
       [ 8,  1],
       [12,  6],
       [ 6,  1]])

In [58]:
np.hstack((a,a2))

array([[ 2, 98,  8,  1],
       [ 9, 56, 12,  6],
       [78,  3,  6,  1]])

In [59]:
a = np.arange(30).reshape(2,15)

In [60]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [61]:
res = np.hsplit(a,3)

In [62]:
res

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [63]:
res[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [64]:
res[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [65]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
b = a > 4

In [67]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [68]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [69]:
a[b] = -1

In [70]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])